In [3]:
pip install folium

Requirement already satisfied: folium in c:\users\hp\anaconda3\lib\site-packages (0.12.1)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (from folium) (2.24.0)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from folium) (1.19.2)
Requirement already satisfied: jinja2>=2.9 in c:\users\hp\anaconda3\lib\site-packages (from folium) (2.11.2)
Requirement already satisfied: branca>=0.3.0 in c:\users\hp\anaconda3\lib\site-packages (from folium) (0.4.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\hp\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import folium

In [9]:
SF_Coordinates = (40.76, -122.25)

In [10]:
map = folium.Map(location=SF_Coordinates)

In [11]:
display(map)

In [4]:
covid_data = pd.read_csv("https://api.covid19india.org/csv/latest/state_wise.csv") 
states_data = pd.read_excel("https://github.com/hrshah211/Corona-Map/raw/main/States.xlsx")

In [6]:
covid_data.head()

,State,Confirmed,Recovered,Deaths,Active,Last_Updated_Time,Migrated_Other,State_code,Delta_Confirmed,Delta_Recovered,Delta_Deaths,State_Notes
0,Total,27366958,24623543,315244,2417274,26/5/2021 23:14:03,10897,TT,210298,280453,3822,NaN
1,Andaman and Nicobar Islands,6901,6573,108,220,26/05/2021 21:54:02,0,AN,23,29,2,NaN
2,Andhra Pradesh,1627390,1424859,10427,192104,26/05/2021 18:28:06,0,AP,18285,24105,99,NaN
3,Arunachal Pradesh,25376,21765,107,3504,26/05/2021 23:14:04,0,AR,374,190,3,[July 25]: All numbers corresponding to Papum ...
4,Assam,386870,329634,3005,52884,26/05/2021 21:54:03,1347,AS,5699,6266,90,[Jan 1]: 1347 cases i.e Covid +'tive patients ...

In [7]:
states_data.head()

                        States   Latitude  Longitude
0  Andaman and Nicobar Islands  11.667026  92.735983
1               Andhra Pradesh  14.750429  78.570026
2            Arunachal Pradesh  27.100399  93.616601
3                        Assam  26.749981  94.216667
4                        Bihar  25.785414  87.479973

In [8]:
covid_trunc = covid_data.iloc[1:]

In [10]:
covid_trunc.head()

,State,Confirmed,Recovered,Deaths,Active,Last_Updated_Time,Migrated_Other,State_code,Delta_Confirmed,Delta_Recovered,Delta_Deaths,State_Notes
1,Andaman and Nicobar Islands,6901,6573,108,220,26/05/2021 21:54:02,0,AN,23,29,2,NaN
2,Andhra Pradesh,1627390,1424859,10427,192104,26/05/2021 18:28:06,0,AP,18285,24105,99,NaN
3,Arunachal Pradesh,25376,21765,107,3504,26/05/2021 23:14:04,0,AR,374,190,3,[July 25]: All numbers corresponding to Papum ...
4,Assam,386870,329634,3005,52884,26/05/2021 21:54:03,1347,AS,5699,6266,90,[Jan 1]: 1347 cases i.e Covid +'tive patients ...
5,Bihar,698329,662491,4845,30992,26/05/2021 21:18:03,1,BR,2603,6641,99,NaN

In [12]:
states_data.columns = ['State','Latitude','Longitude']

In [14]:
states_data.head()

                         State   Latitude  Longitude
0  Andaman and Nicobar Islands  11.667026  92.735983
1               Andhra Pradesh  14.750429  78.570026
2            Arunachal Pradesh  27.100399  93.616601
3                        Assam  26.749981  94.216667
4                        Bihar  25.785414  87.479973

In [15]:
merged_data = pd.merge(covid_trunc.sort_values(['State']),states_data.sort_values(['State']))

In [17]:
merged_data.head()

,State,Confirmed,Recovered,Deaths,Active,Last_Updated_Time,Migrated_Other,State_code,Delta_Confirmed,Delta_Recovered,Delta_Deaths,State_Notes,Latitude,Longitude
0,Andaman and Nicobar Islands,6901,6573,108,220,26/05/2021 21:54:02,0,AN,23,29,2,NaN,11.667026,92.735983
1,Andhra Pradesh,1627390,1424859,10427,192104,26/05/2021 18:28:06,0,AP,18285,24105,99,NaN,14.750429,78.570026
2,Arunachal Pradesh,25376,21765,107,3504,26/05/2021 23:14:04,0,AR,374,190,3,[July 25]: All numbers corresponding to Papum ...,27.100399,93.616601
3,Assam,386870,329634,3005,52884,26/05/2021 21:54:03,1347,AS,5699,6266,90,[Jan 1]: 1347 cases i.e Covid +'tive patients ...,26.749981,94.216667
4,Bihar,698329,662491,4845,30992,26/05/2021 21:18:03,1,BR,2603,6641,99,NaN,25.785414,87.479973

In [18]:
map = folium.Map(location = (21.146039, 79.085036), zoom_start = 5)

In [2]:
color_set = 'red'
for i in range(len(merged_data)):
    if merged_data.loc[i,'Active'] > 0, tooltip=merged_data.loc[i,'State'], icon=folium.Icon(color=color_set).add_to(map)

SyntaxError: invalid syntax (<ipython-input-2-2a4aaf00a1bc>, line 3)